# Generated by Django 6.0 on 2025-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_attendance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='hr_attendan_date_3a46d7_idx'),
        ),
    ]
